name: CI Build

on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ["1.8", "1.10", nightly]
        julia-arch: [x64, x86, aarch64]
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        exclude:
          - os: ubuntu-latest
            julia-arch: aarch64
          - os: windows-latest
            julia-arch: aarch64
          - os: macos-13
            julia-arch: x86
          - os: macos-13
            julia-arch: aarch64
          - os: macos-latest
            julia-arch: x86
          - os: macos-latest
            julia-arch: aarch64
            julia-version: 1.8

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
